<!DOCTYPE html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Konfigurasi Base URL</title>@fonts<link rel="stylesheet" href="{{ asset('css/app.css') }}"></head>
<body class="integration-config-page setup-page min-h-screen bg-[#f4f7fb] text-slate-900 lg:h-dvh lg:overflow-hidden"><div class="min-h-screen lg:grid lg:h-dvh lg:grid-cols-[220px_minmax(0,1fr)]">
<aside class="relative overflow-hidden bg-[#071325] text-white"><div class="absolute inset-0 bg-[linear-gradient(180deg,_#081426_0%,_#071220_100%)]"></div><div class="relative flex h-full flex-col px-[5px] py-5"><div class="flex items-center gap-4"><div class="flex h-12 w-12 items-center justify-center rounded-2xl bg-cyan-400/20 text-cyan-300">+</div><h1 class="text-xl font-semibold">Bridging Monitor</h1></div><nav class="mt-6 flex-1 overflow-y-auto"><a href="{{ url('/') }}" class="mb-2 flex items-center gap-3 rounded-xl px-2 py-2.5 text-sm text-slate-300 hover:bg-white/5"><span class="flex h-7 w-7 items-center justify-center">⌂</span><span>Dashboard</span></a>@include('partials.setup-sidebar-complete') @include('partials.setup-clinic-menu')</nav></div></aside>
<main class="flex min-h-0 flex-col overflow-hidden"><header class="app-page-header"><div class="flex items-center justify-between px-4 py-2.5"><div><h2 class="text-base font-semibold">Base URL BPJS</h2><div class="mt-1 text-xs text-slate-500">Konfigurasi Bridging &gt; Base URL BPJS</div></div>@include('partials.clinic-selector')</div></header><div class="flex-1 overflow-auto p-4">
<section class="rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="flex items-center justify-between border-b px-5 py-4"><div><h3 class="font-semibold">Alamat Layanan BPJS</h3><p class="mt-1 text-xs text-slate-500">Konfigurasi global yang digunakan seluruh klinik.</p></div>@unless($configurations->isNotEmpty())<button data-modal-open="base-url-create" class="rounded-xl bg-blue-600 px-4 text-xs font-semibold text-white">+ Tambah Base URL</button>@endunless</div><div class="overflow-x-auto"><table class="w-full text-left text-sm"><thead class="bg-slate-50 text-xs text-slate-500"><tr><th class="px-5 py-3">Base URL PCare</th><th>Base URL Antrean</th><th class="pr-5 text-right">Aksi</th></tr></thead><tbody>
@forelse($configurations as $configuration)<tr class="border-t"><td class="max-w-md break-all px-5 py-4">{{ $configuration->base_url_pcare }}</td><td class="max-w-md break-all">{{ $configuration->base_url_antrean }}</td><td class="pr-5 text-right"><button data-modal-open="base-url-edit-{{ $configuration->id }}" class="rounded-lg border px-3 text-xs font-semibold text-blue-600">Edit</button> <form method="POST" action="{{ route('configurations.base-url.destroy',$configuration) }}" class="inline" onsubmit="return confirm('Hapus konfigurasi Base URL ini?')">@csrf @method('DELETE')<button class="rounded-lg border px-3 text-xs font-semibold text-rose-600">Hapus</button></form></td></tr>@empty<tr><td colspan="3" class="p-12 text-center text-slate-500">Belum ada konfigurasi Base URL.</td></tr>@endforelse
</tbody></table></div></section>
<x-setup-modal id="base-url-create" title="Tambah Konfigurasi Base URL"><form method="POST" action="{{ route('configurations.base-url.store') }}">@csrf @include('configurations.base-url.form',['configuration'=>null])</form></x-setup-modal>
@foreach($configurations as $configuration)<x-setup-modal id="base-url-edit-{{ $configuration->id }}" title="Edit Base URL BPJS"><form method="POST" action="{{ route('configurations.base-url.update',$configuration) }}">@csrf @method('PUT') @include('configurations.base-url.form')</form></x-setup-modal>@endforeach
</div></main></div>@if(session('success') || $errors->any())<div class="fixed right-4 bottom-4 z-[100] rounded-2xl border bg-white px-5 py-4 text-sm shadow-xl">{{ session('success') ?? $errors->first() }}</div>@endif
<script>document.querySelectorAll('[data-modal-open]').forEach(b=>b.addEventListener('click',()=>document.getElementById(b.dataset.modalOpen)?.showModal()));document.querySelectorAll('[data-modal-close]').forEach(b=>b.addEventListener('click',()=>b.closest('dialog')?.close()));document.querySelectorAll('[data-dropdown-toggle]').forEach(b=>{const p=b.parentElement.querySelector('[data-dropdown-panel]'),i=b.querySelector('[data-dropdown-icon]');b.addEventListener('click',()=>{const o=b.getAttribute('aria-expanded')==='true';b.setAttribute('aria-expanded',o?'false':'true');p?.classList.toggle('hidden',o);i?.classList.toggle('rotate-180',!o);});});</script><script src="{{ asset('js/sidebar-state.js') }}"></script></body></html>
